version: "3"

x-app-service: &default-app
  build: .
  command: ''

  volumes:
    - .:/code:delegated
    - node_modules:/code/node_modules:delegated

services:
  app:
    <<: *default-app

  portfolios_backend:
    <<: *default-app
    command: bash -c "npm run build && npm run start:portfolios:backend"
    ports:
      - ${PORTFOLIOS_BACK_PORT}:${PORTFOLIOS_BACK_PORT}

  portfolios_frontend:
    <<: *default-app
    command: bash -c "npm run start --prefix ./src/Apps/portfolios/frontend"
    ports:
      - ${PORTFOLIOS_FRONT_PORT}:${PORTFOLIOS_FRONT_PORT}
 
volumes:
  node_modules:
  esdata:
    driver: local